#!/bin/bash
echo "🔍 Checking GitHub Pages Status..."
echo ""
echo "1. Check if GitHub Pages is enabled:"
echo "   👉 https://github.com/gunainvestor/GenAI_life-problem-solver/settings/pages"
echo ""
echo "2. Check Actions workflow status:"
echo "   👉 https://github.com/gunainvestor/GenAI_life-problem-solver/actions"
echo ""
echo "3. Test the site URL:"
echo "   👉 https://gunainvestor.github.io/GenAI_life-problem-solver"
echo ""
echo "Current status: Site returns 404 (not deployed yet)"
echo ""
echo "📋 What to do:"
echo "   1. Go to Settings → Pages"
echo "   2. Under 'Source', select 'GitHub Actions'"
echo "   3. Click 'Save'"
echo "   4. Wait 1-2 minutes"
echo "   5. Check Actions tab for deployment status"
