name: Build & Release Signed APK

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'app/build.gradle.kts'
      - 'app/src/**'
      - 'gradle/**'

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Decrypt release keystore
        env:
          KEYSTORE_B64: ${{ secrets.RELEASE_KEYSTORE_B64 }}
        run: |
          echo "$KEYSTORE_B64" | base64 -d > app/release-keystore.jks

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build signed release APK
        run: ./gradlew assembleRelease

      - name: Get version name
        id: version
        run: |
          VERSION_NAME=$(grep versionName app/build.gradle.kts | head -1 | cut -d'"' -f2)
          echo "version=$VERSION_NAME" >> $GITHUB_OUTPUT

      - name: Rename APK with version
        run: |
          cp app/build/outputs/apk/release/app-release.apk LifeProblemSolver-v${{ steps.version.outputs.version }}-release.apk

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: LifeProblemSolver-APK-v${{ steps.version.outputs.version }}
          path: LifeProblemSolver-v${{ steps.version.outputs.version }}-release.apk
          retention-days: 30

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: LifeProblemSolver-v${{ steps.version.outputs.version }}-release.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ **APK Build Complete!**
              
              **Version:** ${{ steps.version.outputs.version }}
              **APK:** LifeProblemSolver-v${{ steps.version.outputs.version }}-release.apk
              
              Download the APK from the Actions artifacts tab above.`
            }) 